services:
  wrongnotes_backend:
    build:
      dockerfile: ./audio_brainstorm/Dockerfile
    image: play-the-wrong-notes:development
    ports:
      - "8000:8000"
    depends_on:
      - wrongnotes_db 
  
  wrongnotes_db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  wrongnotes_frontend:
    build:
      context: ./wrong_notes
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - wrongnotes_backend

volumes:
  db_data: